### ISSUE TITLE
Security issue in email verification

### ISSUE THREAD

**Issue by andresriancho** [eeg3/workspaces-portal#18]
https://github.com/eeg3/workspaces-portal/blob/master/lambda/cognito-domainVerify/cogDomainVerify.js#L9 is insecure, you should be using `endswith` instead of `include`.

With the current code, if `approvedDomain` is `company.com` , an attacker could register `company.com.ar` (or any other domain) and bypass the registration filter.

**Comment by eeg3** [comment]
Thanks for this find & fix! Updated in commit: [383bdd4](https://github.com/eeg3/workspaces-portal/commit/383bdd4fe2f651dc43e747c1542bb4235f1d5f2f)
