### ISSUE TITLE
The Dashboard shows the last instance running

### ISSUE THREAD

**Issue by durwasa-chakraborty** [eeg3/workspaces-portal#19]
**STR -** 
Create 4-5 workspaces instances for different users.

**Expected Outcome -**
The provisioned instance corresponding to that user should be shown.

**Current Outcome -** 
The last running instance of the AWS workspaces list is shown

**Possible Diagnosis -** 
There is a `for` loop [here](https://github.com/eeg3/workspaces-portal/blob/master/lambda/workspaces-control/workspaces-control.js#L45) which runs through completely even before the async methods `describeWorkspaces` and `describeTags` are called and completed.

**Comment by durwasa-chakraborty** [comment]
@eeg3 

The proposed solution is very naive as it involves some boolean flags as mutex
https://github.com/eeg3/workspaces-portal/pull/20

I would really appreciate if you could suggest me a better solution.

**Comment by eeg3** [comment]
Thanks @durwasa-chakraborty -- I will check out this issue shortly.

**Comment by eeg3** [comment]
This should now be fixed -- the problem was that the describeTagsParams variable was being changed outside the loops' inside functions -- resolved by limiting function scope.

Resolved in: [3e5e950](https://github.com/eeg3/workspaces-portal/commit/3e5e95062a48b5ef5da3721e8a689519ccd774e4)
